services:
  postgres:
    image: postgres:17
    container_name: learn-postgres

    environment:
      POSTGRES_DB: learn
      POSTGRES_USER: learn_user
      POSTGRES_PASSWORD: learn_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres_data: